Django/practice/1006/movie/urls.py
from django.urls import path 
from . import views

app_name = 'movie'

# 기본이 get임

urlpatterns = [
  # http://127.0.0.1:8000/movie/
  path('', views.index, name='index'),
  path('create/', views.create, name='create'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
]

Django/practice/1006/movie/models.py
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill
from django.db import models

# Create your models here.

class Movie(models.Model): # Movie모델 클래스는 models에 있는 model을 상속받아서 만듦 => 설계는 했지만 기능 자체는 상속을 받아 사용하고 싶기 때문
    title = models.CharField(max_length=20)
    summary = models.TextField()
    running_time = models.IntegerField()
    content = models.TextField()
    image = ProcessedImageField(upload_to='images/', blank=True, # true인 경우, 필드를 비워둘 수 있음
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',
                                options={'quality':80}) # 항상 업로드하는 것은 아니니 blank=true # 사용자가 입력한 이미지를 어디로 업로드 할 것이냐!
    thumbnail = ProcessedImageField(upload_to='images/', blank=True,
                                    processors=[ResizeToFill(1200,960)], 
                                    format='JPEG',
                                    options={'quality':80})

Django/practice/1006/movie/forms.py
from django import forms
from .models import Movie

# 선언된 모델에 따른 필드구성
# 모델 폼 로직: 사용자에게 html form을 제공, 입력 받은 데이터를 처리
# 1. form 생성
# 2. 유효성 검사

class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = ['title', 'summary', 'running_time', 'content', 'image', 'thumbnail']

Django/practice/1006/movie/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from movie.forms import MovieForm
from .models import Movie


# Create your views here.

def index(request):
    movies = Movie.objects.order_by('-pk')
    context = {
        'movies':movies
    }
    return render(request, 'movie/index.html', context)

@login_required
def create(request):
    # 실제 db에 저장하는 로직
    if request.user.is_authenticated: # 로그인해야지 글작성할 수 있지만 주소에 create입력하면 넘어감, 그럴수 없도록(create주소를 입력해도 넘어가지 않도록) 서버에서 막아주는 것
        if request.method == 'POST':

            movie_form = MovieForm(request.POST, request.FILES) # 사용자가 작성한 내용, 이미지가 안들어갔을 때, 여기를 확인!(파일은 별도의 객체를 가지고 있기 때문에 request.files)
            if movie_form.is_valid():
                movie_form.save()
                messages.success(request, '글 작성 완료!')
                return redirect('movie:index')
        else:
            movie_form = MovieForm() # 틀만 제공
        context = {
            'movie_form': movie_form
        }
        return render(request, 'movie/new.html', context)
    else: 
        return redirect('accounts:login')
        # 여러 해결책이 있음 1.접근 잘못했다는 페이지 렌더 2.리턴 리다이렉트 로그인페이지


def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie' : movie
    }
    return render(request, 'movie/detail.html', context)



@login_required # 로그인이 필요해! /http://localhost:8000/accounts/login/?next=/movie/1/update/(겟 요청)와 login url이 다른이유는? => 어카운트 뷰에서 안쓰기 때문
# 위 데코레이터는 로그인을 사용자가 요구 되는상황에 있어서 실제로 로그인 페이지로 보내주고 그 이후의 행동을 뷰 함수의 추가적인 처리로써 해결 할 수 있음 
def update(request, pk):
    movie = Movie.objects.get(pk=pk)

    if request.method == 'POST':
        movie_form = MovieForm(request.POST, request.FILES, instance=movie) #  movie = Movie.objects.get(pk=pk)
        if movie_form.is_valid():
            movie_form.save()
            messages.success(request, '글 수정 완료!')
            return redirect('movie:detail', movie.pk)
    else:
        movie_form  = MovieForm(instance=movie)

    context = {
        'movie_form' : movie_form
        }
    return render(request, 'movie/update.html', context)


def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('movie:index')
    context = {
        'movie':movie
    }
    return render(request, 'movie/index.html', context)

Django/practice/1006/movie/templates/movie/detail.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{ movie.pk }}번 게시글</h1>
  <p>{{ movie.title}}
    |
    {{ movie.running_time }}</p>
  <p>{{ movie.content }}</p>
  {% if movie.image %}
    <img src="{{ movie.image.url }}" alt="{{ movie.image }}" width="400" ,="," height="300">
  {% endif %}
  <a href="{% url 'movie:update' movie.pk %}">수정하기</a>

  <form action="{% url 'movie:delete' movie.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">리뷰 삭제</button>
  </form>
{% endblock content %}

Django/practice/1006/movie/templates/movie/index.html
{% extends 'base.html' %}
{% block content %}
  <h1>영화 정보</h1>
  {% if request.user.is_authenticated %}
    <a class='btn btn-primary my-3' href="{% url 'movie:create' %}">영화 정보 등록</a>
  {% endif %}

  <div class="row">
    {% for movie in movies %}
      <div class="col-4">
        <div class="card">
          {% if movie.thumbnail %}
            <img src="{{ movie.thumbnail.url }}" class="card-img-top" alt="...">
          {% else %}
            <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class="card-img-top">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ movie.title }}</h5>
            <a class='btn btn-primary my-3' href="{% url 'movie:detail' movie.pk%}">Go somewhere</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

Django/practice/1006/movie/templates/movie/new.html
{% extends 'base.html' %}{% load django_bootstrap5 %}
{% block content %}

  <!-- form : 사용자에게 양식을 제공하고 값을 받아서(input : name, value) 서버에 전송(form : action, method)-->
  <form action="{% url 'movie:create' %}" method="POST" enctype="multipart/form-data">
    <!--지금있는 페이지에 포스트로 들어가겠다-->
    <!--action: 서버에 전송-->
    {% csrf_token %}
    {% bootstrap_form movie_form %}
    <!-- <label for="title">제목 : </label> <input type="text" name="title" id="title" required> <label for="content">내용 : </label> <textarea name="content" id="content" cols="30" rows="10" required></textarea> -->
    {% bootstrap_button content="ok" button_type="submit" button_class="btn-primary col-3" %}
  </form>
{% endblock content %}

Django/practice/1006/movie/templates/movie/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>글 수정하기</h1>

  <form action="" method="POST" enctype="multipart/form-data">
    <!--detail페이지로 돌아감-->
    {% csrf_token %}
    {% bootstrap_form movie_form %}
    <input type="submit" value="수정"/>
  </form>
{% endblock content %}