Django/practice/0926/articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
]

Django/practice/0926/p_0926/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pratices/', include('pratices.urls')),
    path('posts/', include('posts.urls')),
]

Django/practice/0926/posts/urls.py
from django.urls import path
from . import views

"""
메인(r): 게시글 목록(/posts/) / 게시글 상세
작성(c): 글을 작 성하는 페이지(/posts/new/) / 작성완료
수정(u): 글을 수정하는 페이지 / 수정 완료
삭제(d): 글을 삭제 완료 
"""

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'), 
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>', views.delete, name='delete'),
    # 어떤 주소로(디테일)로 요청하면 어떤 뷰(디테일) 함수를 응답할까? 
    path('detail/<int:pk_>', views.detail, name='detail'),
    path('edit/<int:pk_>', views.edit, name='edit'),
    path('update/<int:pk_>', views.update, name='update')
    # 주소를 요청하면 업데이트 함수를 응답할것임
]

Django/practice/0926/pratices/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('is-odd-even/<number>/', views.number),
    path('calculate/<a>/<b>', views.num),
    path('name/', views.name),
    path('answer/', views.answer),
    path('lorem_input/', views.lorem_input),
    path('lorem_result/', views.lorem_result),
]

Django/practice/0926/articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    content = models.TextField()
    

Django/practice/0926/posts/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

Django/practice/0926/pratices/models.py
from django.db import models

# Create your models here.

Django/practice/0926/articles/views.py
from django.shortcuts import render
from .models import Article


# Create your views here.

guestbook = []

def index(request):
    # db에서 가져오기
    guestbook = Article.objects.all()
    # select * from articles;
    return render(request, 'articles/index.html', {'guestbook': guestbook})

def create(request):
    content = request.GET.get('content')
    # guestbook.append(content)
    # db에 저장
    # 아티클 디비에서 레코드 만들기
    Article.objects.create(content=content)
    return render(request, 'articles/create.html', {'content': content})

Django/practice/0926/posts/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.



# 첫번째 리드: 글에 데이터목록을 출력
def index(request):
    # 모든 글 목록 보여준다
    # 1. 디비에서 모든 글 불러온다
    posts = Post.objects.all()
    # 2. 템플릿에 보내준다. 
    context = {
        'posts' : posts
    }
    return render(request, 'posts/index.html', context)

# 두번째 리드: 하나의 데이터에 대한 정보를 출력
# 1. 클릭할 것에 a태그 링크를 걸어줌, 삭제를 할 때 처럼 내가 클릭한 글의 pk값을 동적인자로 전달해야함
# 2. url만들기
# 3. pk값을 이동시키면서 뷰에서 가져오고, 템플릿에서 출력(유알엘 > 뷰 > 템플릿)
def detail(request, pk_):
    # get() 메소드를 사용해서 특정 pk의 데이터를 불러온다. 패쓰와 동일해야함
    # 불러온 데이터를 변수에 할당
    post = Post.objects.get(pk = pk_)

    context = {
        'post' : post,
    }
   # 템플릿에서 변수를 사용하기 위해 컨텍스트를 넣어줌
    return render(request, 'posts/detail.html', context)

def new(request):
    return render(request, 'posts/new.html')


def edit(request, pk_):
    # get메소드를 사용해서 특정 pk데이터를 불러온다. 
    post = Post.objects.get(pk = pk_)
    context = {
        "post" : post,

    }
    return render(request, 'posts/edit.html', context)


def create(request):
    
    # 1. 파라미터로 날라온 데이터를 받아서 

    title = request.GET.get('title')
    content = request.GET.get('content')

    # 2. 디비에 저장

    Post.objects.create(title=title, content=content)
    context = {
        'title' : title,
        'content' : content,
    }

    return redirect('posts:index')


# read+ create + 알파
# read : 수정페이지의 디테일을 출력
def update(request, pk_):
    # 업데이트 할 특정 데이터를 불러온다. => pk_를 사용해서

    post = Post.objects.get(pk = pk_)
    # create처럼 데이터를 받아와야함

    title_ = request.GET.get('title')
    content_ = request.GET.get('content')

    # 데이터 수정
    # 내가 불러온 것을 입력 받은 것으로 바꿈
    post.title = title_
    post.content = content_

    post.save()

    # 데이터의 디테일 페이지로 리다이렉트
    return redirect('posts:detail', post.pk) # 인덱스의 첫번째 유알엘과 똑같



def delete(request, pk):
    # pk에 해당하는 글 삭제
    Post.objects.get(id=pk).delete()

    return redirect('posts:index')

# 1.사용자가 수정하려면 수정 페이지가 있어야함
# 2.수정버튼 누르면 변경사항을 반영할 뷰가 필요함
# 3.edit => new, update => create와 비슷

Django/practice/0926/pratices/views.py
from multiprocessing import context
from unittest import result
from django.shortcuts import render
import random

# Create your views here.

def number(request, number):

    num=int(number)
    text = 0
    if num==0:
        text='0'
    elif num%2==1:
        text='홀수'
    elif num%2==0:
        text='짝수'
    

    context = {
        'num' : num,
        'text' : text,
    }

    return render(request, 'pratices/is-odd-even.html', context)


def num(request, a, b):
    a = int(a)
    b = int(b)
    result_1 = a + b
    result_2 = a - b
    result_3 = a*b
    result_4 = a//b

    context = { 
        'result_1' : result_1,
        'result_2' : result_2,
        'result_3' : result_3,
        'result_4' : result_4,
        'a' : a,
        'b' : b,
    
    }

    return render(request, 'pratices/calculate.html', context)


def name(request):
    return render(request, 'pratices/name.html')


def answer(request):
    name = request.GET['name']

    animals = ['말', '강아지', '토끼', '호랑이']
    animal = random.choice(animals)

    context = {
        'name' : name,
        'animal' : animal,
    }

    return render(request, 'pratices/answer.html', context)

def lorem_input(request):
    return render(request, 'pratices/lorem_input.html')


def lorem_result(request):
    name1 = int(request.GET['a'])
    name2 = int(request.GET['b'])

    word = ['바나나', '딸기', '사과', '배']
    
    context = {
        'c' : []
        
    }

    for i in range(name1):
        temp = []
        for j in range(name2):
            temp.append(random.choice(word)) 
        context['c'].append(temp)

    return render(request, 'pratices/lorem_result.html', context)






    

Django/practice/0926/articles/templates/articles/create.html
{% extends 'base.html' %} {% block content %}
<h1>작성완료.</h1>
<p>작성내용: {{ content }}</p>
<a href="{% url 'index' %}">방명록으로 돌아가기</a>
{% endblock %}

Django/practice/0926/articles/templates/articles/index.html
{% extends 'base.html' %} {% block content %}
<body>
  <div>
    <h1>방명록</h1>
  </div>
  <div>
    <h2>글 목록</h2>
    {% for content in guestbook %}
    <p>{{ content.content }}</p>
    {% endfor %}
  </div>
  <div>
    <h2>글 작성</h2>
    <form action="{% url 'create' %}">
      <input type="text" name="content" />
      <input type="submit" />
    </form>
  </div>
</body>
{% endblock %}

Django/practice/0926/posts/templates/posts/create.html
{% extends 'base.html' %} {% block content %}
<h1>글 작성완료</h1>
<p>제목: {{ title }}</p>
<p>내용: {{ content }}</p>

<a href="{% url 'posts:index' %}">목록으로</a>
{% endblock %}

Django/practice/0926/posts/templates/posts/detail.html
{% extends 'base.html' %} {% block content %}
<h1>detail.html</h1>
<h1>제목:{{ post.title }}</h1>
<h1>내용:{{ post.content }}</h1>
{% endblock %}

Django/practice/0926/posts/templates/posts/edit.html
{% extends 'base.html' %} {% block content %}
<h1>글 수정</h1>
<!--특정 pk를 가진 데이터를 불러오기 위해 pk를 동적인자로 전달-->
<form action="{% url 'posts:update' post.pk %}">
  제목: <input type="text" name="title" value="{{ post.title }}" /><br />
  내용: <input type="text" name="content" value="{{ post.content }}" />
  <input type="submit" />
</form>
{% endblock %}

Django/practice/0926/posts/templates/posts/index.html
{% extends 'base.html' %} {% block content %}
<h1>게시판</h1>
<ul>
  {% for post in posts %}
  <li>
    id: {{ post.id }}
    <a href="{% url 'posts:detail' post.pk %}">제목: {{ post.title }}</a>
    <a href="{% url 'posts:edit' post.pk %}"> [수정] </a>
    <!--유알엘 뒤에 동적인자 전달-->
    <a href="{% url 'posts:delete' post.pk %}"> [삭제] </a>
  </li>
  {% endfor %}
</ul>

<a href="{% url 'posts:new' %}">새 글쓰기</a>
{% endblock %}

Django/practice/0926/posts/templates/posts/new.html
{% extends 'base.html' %} {% block content %}
<h1>새글 쓰기</h1>
<form action="{% url 'posts:create' %}">
  제목: <input type="text" name="title" /><br />
  내용: <input type="text" name="content" />
  <input type="submit" />
</form>
{% endblock %}

Django/practice/0926/pratices/templates/pratices/answer.html
{% extends 'base.html' %} {% block content %}
<h1>{{ name }}님, 당신의 전생은 {{ animal }}입니다.</h1>
{% endblock %}

Django/practice/0926/pratices/templates/pratices/calculate.html
{% extends 'base.html' %} {% block content %}
<h1>{{ a }} + {{ b }} = {{ result_1 }}</h1>
<h1>{{ a }} - {{ b }} = {{ result_2 }}</h1>
<h1>{{ a }} * {{ b }} = {{ result_3 }}</h1>
<h1>{{ a }} // {{ b }} = {{ result_4 }}</h1>
{% endblock %}

Django/practice/0926/pratices/templates/pratices/is-odd-even.html
{% extends 'base.html' %} {% block content %}
<h1>{{ num }}은 {{ text }}입니다.</h1>
{% endblock %}

Django/practice/0926/pratices/templates/pratices/lorem_input.html
{% extends 'base.html' %} {% block content %}
<form action="/lorem_result">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">문단의 수</label>
    <input
      name="a"
      type="number"
      class="form-control"
      id="exampleInputEmail1"
      style="width: 400px"
    />
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail2" class="form-label">문단별 단어의 수</label>
    <input
      name="b"
      type="number"
      class="form-control"
      id="exampleInputEmail2"
      style="width: 400px"
    />
  </div>
  <button type="submit" class="btn btn-primary">생성</button>
</form>
{% endblock %}

Django/practice/0926/pratices/templates/pratices/lorem_result.html
{% extends 'base.html' %} {% block content %} {% for i in c %}
<p class="border-bottom fw-bold">{% for j in i %} {{ j }} {% endfor %}</p>
{% endfor %} {% endblock %}

Django/practice/0926/pratices/templates/pratices/name.html
{% extends 'base.html' %} {% block content %}
<form action="/answer">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label"
      >이름을 입력하세요.</label
    >
    <input
      name="name"
      type="text"
      class="form-control"
      id="exampleInputEmail1"
      style="width: 400px"
    />
  </div>
  <button type="submit" class="btn btn-primary">전생 확인하기</button>
</form>
{% endblock %}