Django/practice/1020/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path("", views.index, name="index"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

Django/practice/1020/articles/urls.py
from django.urls import path 
from . import views

app_name = 'articles'

urlpatterns = [
  # http://127.0.0.1:8000/articles/
  path('', views.index, name='index'),
  path('<int:pk>/', views.detail, name='detail'),
  path('create/', views.create, name='create'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
  path('<int:pk>/comments/', views.comment_create, name='comment_create'),
  path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
  path('<int:pk>/like/', views.like, name='like'),
]

Django/practice/1020/pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/practice/1020/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    {% bootstrap_css %}
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Nanum+Gothic:wght@800&display=swap');

      body {
        font-family: 'Nanum Gothic', sans-serif;
      }
    </style>
  </head>

  <nav class="navbar navbar-expand-lg bg-danger">
    <div class="container-fluid ">
      <a class="navbar-brand " href="{% url 'articles:index' %}">home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:detail' request.user.pk %}">{{ request.user }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
            </li>
          {% endif %}
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <div class="container my-5">
    {% block body %}{% endblock body %}
  </div>
  {% bootstrap_javascript %}
</body>

</html>