Django/practice/1006/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('<int:pk>/', views.detail, name='detail'),
]

# 프로필페이지: /accounts/2/
# 뷰: 디테일
# 템플릿 반환: 사용자정보(유저네임)

# 로그인 기능 -> aticle create / user create와 비슷
# 1. url: GET/accounts/login/ 
# -> 처리(사용자에게 form을 제공) 
# 2. url: POST/accounts/login/요청 들어오면 
# -> 처리(로그인) 로직 처리(사용자인지 확인하고 장고 세션 테이블에 저장), 쿠키주기
# ->(성공) 로그인 완료 되면 게시글 목록 페이지로 리다이렉트
# ->(실패) 로그인 form

# 로그인 행위: 세션 테이블에 무언가 저장, 쿠키 떨궈줌, 그 정보 담겨진건 리퀘스트 객체
# 로그인과 관련 된 폼은 어센틱케이션폼 => 그냥 폼임(모덷 폼 아님)
# 아티클 직접 만든 모델폼, 회원가입은 장고 내부 폼을 활용해서 모델폼, 로그인은 장고가 만든 폼 활용이지만 그냥 폼을 활용한 것임


# 10/13(목)-회원정보 수정
# 1. url: accounts/<int:Pk>/update/ 회원정보 수정을 하는데 유저별로 할 필요가 없음
# => 로그인한 유저의 정보를 수정하면 됨
# url : /accounts/update 사용하되, 로그인한 사용자에 한해, 로그인한 사용자의 아이디값을 받아서 처리
# GET 요청: form
# post 요청: 실제 수정작업 => 작업 후 개인 프로필페이지로 보내줌(너는 수정한 것을 상세페이지 가서 확인해!)
# 기능(뷰)
# 2. form: 우리는 무슨폼을 주면 될까? => 유저와 연결 된 모델폼 사용하면 됨

# 비밀번호가 바꾸고 로그인 유지하고 싶으면 별도작업 필요 => 수업자료에 나온걸 임포트함
# 탈퇴 하면서 세션 정보 함께 지우고 싶은 경우 = 탈퇴 > 로그아웃 시키면 됨

Django/practice/1006/movie/urls.py
from django.urls import path 
from . import views

app_name = 'movie'

# 기본이 get임

urlpatterns = [
  # http://127.0.0.1:8000/movie/
  path('', views.index, name='index'),
  path('create/', views.create, name='create'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
]

Django/practice/1006/pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movie.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 이미지 업로드는 
# 1. 저장하고 있었던 것은 텍스트/숫자, 이번에는 이미지를 저장
# 이미지 받기 위해 html form에서 설정(enctype), view(reuqest.filese), setting
# 2. 보여주기는 스태틱과 닮아있음, 셋팅에서 루트와 url설정 필요 
# 배포에서는 스태틱 모으는 작업할 것임, 이미지는 미디어 루트/url에서 설정해야함(이미지를 서버에서 보여주는 방법이기 떄문)
# 3. 서빙을 하는애를 만들고 있고, 그것이 서버임

Django/practice/1006/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_css %}
    <title>Document</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'movie:index' %}">
          <img src="{% static 'movie/logo.png' %}" alt="Logo" class="d-inline-block align-text-top"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'movie:index' %}">목록</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'movie:create' %}">리뷰작성</a>
              </li>
            {% endif %}
            <!--로그인을 하지 않는 상태에서만 회원가입이 보여져야함-->
            {% if request.user.is_authenticated %}
              <!--request객체는 user의객체이며, user객체가 가지고 있는 is_au이라는 읽을 수있는 속성-->
              <!--user가 로그인이 되었다면-->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
              </li>

            {% endif %}
          </ul>
        </div>
      </nav>
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

      {% if request.user.is_authenticated %}
        <h1>{{ request.user }}</h1>
      {% endif %}
      <!--setting>templates>contrib.auth.context_processors.auth 여기에 user가 들어가있어서 그걸 사용한 것임-->
      <div class="container">
        {% block content %}{% endblock %}
      </div>
      {% bootstrap_javascript %}
    </body>

  </html>